### ISSUE TITLE
I can't find the author. This text animation does not support Chinese

### ISSUE THREAD

**Issue by dong-lufei** [loadingio/loading.css#10]
https://loading.io/animation/text/

**Comment by zbryikt** [comment]
hi, you can contact with us through this mail: contact@loading.io
github is for developer and corresponding open source projects so I will close this issue for now.

animated text generator currently only support latin letters for now and will add cjk fonts in the future; additionally, you can also try uploading your own fonts and it should be able to make cjk letters work. :)
