### ISSUE TITLE
Install fails with yarn: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by fapdash** [loadingio/loading.css#3]
Yarn fails on purpose if the engine version doesn't match: https://github.com/yarnpkg/yarn/issues/3430

Could we maybe change the versions to not point to a specific version?
https://github.com/loadingio/loading.css/blob/5e2f52e6dc899bd238d9d19f3e97ef9675b69f45/package.json#L13

**Comment by omaraltayyan** [comment]
.

**Comment by zbryikt** [comment]
seems to have been resolved by 3fa8cae33005942059dc1c7dd7187ec0dd9bfd04
